---
name: "Build and publish Docker Image"

on:
  push:
    tags:
      - "v*.*.*"

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "${{ github.repository }}"

jobs:
  build-and-push:
    name: "Build and push Docker Image"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      packages: "write"

    steps:
      - id: "checkout"
        name: "Checkout repository"
        uses: "actions/checkout@v4"

      - id: "qemu"
        name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v3"

      - id: "buildx"
        name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v3"

      - id: "meta"
        name: "Extract metadata for Docker"
        uses: "docker/metadata-action@v5"
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - id: "login"
        name: "Log in to GitHub Container Registry"
        uses: "docker/login-action@v3"
        with:
          registry: "${{ env.REGISTRY }}"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - id: "build-and-push"
        name: "Build and push Docker image"
        uses: "docker/build-push-action@v5"
        with:
          context: "."
          file: "./docker/Dockerfile"
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
          cache-from: "type=gha"
          cache-to: "type=gha,mode=max"
